---
all:
  hosts:
    sonar-01:
      ansible_host: 192.168.33.11
      ansible_ssh_private_key_file: "/home/smm/hw_ansible_02/playbook/id_rsa.pem"
    nexus-01:
      ansible_host: 192.168.33.12
      ansible_ssh_private_key_file: "/home/smm/hw_ansible_02/playbook/id_rsa.pem"
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: vagrant
